version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: npg_WhxO48jVDGCg
      POSTGRES_DB: koyebdb
    ports:
      - 5432:5432
    networks:
      - rafa-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root" ]
      interval: 30s
      retries: 10
      start_period: 60s

  rest_api:
    build:
      context: './rest-with-springboot-and-java'
      dockerfile: Dockerfile
    container_name: rest_api_container
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rafa-network
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://ep-withered-surf-a2si9sf2.eu-central-1.pg.koyeb.app:5432/koyebdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: npg_WhxO48jVDGCg
    ports:
      - 8080:8080
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Waiting for PostgreSQL to be ready..."
        until nc -z db 5432; do
          sleep 2
        done
        java -jar /app.jar

networks:
  rafa-network:
    driver: bridge
