spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ep-withered-surf-a2si9sf2.eu-central-1.pg.koyeb.app:5432/koyebdb
    username: postgres
    password: npg_WhxO48jVDGCg

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    default-property-inclusion: NON_NULL

flyway:
  enabled: false
  url: jdbc:postgresql://ep-withered-surf-a2si9sf2.eu-central-1.pg.koyeb.app:5432/koyebdb
  user: postgres
  password: npg_WhxO48jVDGCg

