name: Deploy Backend

on:
  push:
    branches:
      - main  # Executa o deploy quando há push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'  # Ajuste para a versão que você usa

      - name: Construir a aplicação
        working-directory: Main/rest-with-springboot-and-java
        run: mvn clean package -DskipTests

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir a imagem Docker
        working-directory: Main/rest-with-springboot-and-java
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:latest .

      - name: Enviar a imagem para o Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

      - name: Conectar ao servidor e atualizar o container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
            docker stop backend-container || true
            docker rm backend-container || true
            docker run -d --name backend-container -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

